import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "../component/LoginBtn";
import { auth } from "@/auth";
import LogoutBtn from "@/component/LogoutBtn";
import SignupBtn from "@/component/SignupBtn";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="nav-bar">
          <div className="title">
            <Link href={"/"} className="flex">
              <span>블로그</span>
            </Link>
          </div>
          <div className="nav-items">
            <Link href={"/list"} className="nav-item">
              List
            </Link>
          </div>
          {!!session ? (
            <div className="nav-buttons">
              <Link href={"/write"} className="flex">
                <img src="/icon-write.png" alt="" className="icon-write" />
                {/* (글쓰기) */}
              </Link>
              <Link href={"/mypage"} className="flex">
                <img src="/icon-profile.png" alt="" className="icon-write" />
                {/* <span>({session.user.name}님)</span> */}
                {/* <div className="nav-button white">
                  {session.user.name}의 블로그
                </div> */}
              </Link>
              {/* <LogoutBtn></LogoutBtn> */}
            </div>
          ) : (
            <div className="nav-buttons">
              <LoginBtn></LoginBtn>
              <SignupBtn></SignupBtn>
            </div>
          )}
        </div>
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
