import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "../component/LoginBtn";
import { auth } from "@/auth";
import LogoutBtn from "@/component/LogoutBtn";
import SignupBtn from "@/component/SignupBtn";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="nav-bar">
          <div className="title">
            <Link href={"/"}>
              <img src="/icon-character.png" alt="" />
              <span>일기장</span>
            </Link>
          </div>
          <div className="nav-items">
            <Link href={"/list"} className="nav-item">
              List
            </Link>
          </div>
          {!!session ? (
            <div className="nav-buttons">
              <Link href={"/write"}>
                <img src="/icon-write.png" alt="" className="icon-write" />
              </Link>
              <span>{session.user.name}</span>
              <LogoutBtn></LogoutBtn>
            </div>
          ) : (
            <div className="nav-buttons">
              <LoginBtn></LoginBtn>
              <SignupBtn></SignupBtn>
            </div>
          )}
        </div>
        {children}
        <div className="footer">
          <span>Icons by&nbsp;</span>
          <a href="https://icons8.kr/">Icons8</a>
        </div>
      </body>
    </html>
  );
}
