import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "../component/LoginBtn";
import { auth } from "@/auth";
import SignupBtn from "@/component/SignupBtn";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="top-navigation">
          <div className="top-navigation-inner">
            <h1>블로그</h1>
            <div className="top-navigation-main">
              <Link href={"/guide"} className="nav-item">
                가이드
              </Link>
              <Link href={"/question"} className="nav-item">
                주제모음
              </Link>
              {!!session ? (
                <div className="nav-buttons">
                  <Link href={"/list"} className="nav-item">
                    List
                  </Link>
                  <Link href={"/write"} className="flex">
                    <img src="/icon-write.png" alt="" className="icon-write" />
                  </Link>
                  <Link href={"/mypage"} className="flex">
                    <img
                      src="/icon-profile.png"
                      alt=""
                      className="icon-write"
                    />
                  </Link>
                </div>
              ) : (
                <div className="nav-buttons">
                  <LoginBtn></LoginBtn>
                  <SignupBtn></SignupBtn>
                </div>
              )}{" "}
            </div>
          </div>
        </div>
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
